{{- if not .Values.global.experimental_native_ingress }}
apiVersion: v1
kind: Secret
metadata:
  name: deis-router-dhparam
  labels:
    heritage: deis
type: Opaque
data:
  dhparam: {{ if not (empty .Values.dhparam) }}{{ .Values.dhparam }}{{ else }}LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBMTV6UHBQcElsaTYyUC9aTHFUcHhYdnNHMUtZU2hnbzJUOFpFZ1VzM0NxTjZiSU4xSHU1VwpXNnNVdDRYWXpJNExkSWxRanlFOHZjeWhxdEl6ajIyM1hLalhXQVE1WU5ud2NZU05jVUlyTjh1YThQN2ZmNlF2CnhiWlFMbjRUY1k3N2VWMm1Ecm9MSU5TUlFzZFZGVlpiRUpmK1lOZEFOa2w4dlg5UDlIelVrdm5SaGI5cDJJOXEKWGY5dll1cEVVbXd1K1I2d2pzNnFzUTJ4akVmTGxmcnczaEdrUi9jdjBtT2QvUmVrWWRjbVlISjlUelpkM3NSZgp6cTl3ckw0RWRDNzBUSmNQcERZZXRaWUdKV3Fxa3hpKzM4eGtuV2dtNkN0cE1TdEFHMk5UVWJ2ZmRoTGpid2tmCmU4a2o4M01HalZ5ajNlTktTd0VQYlo5bXJWTFR3VWh6WkQ2bFV3eG1rQ1ZBVXl2MEZmb3BhT29PSXJuNnRUaVIKRWhmdkxZVXQvWkVZK2hPOWpFalp6alAvbEcrOFFpZWpFaW16bjFIbkt4S041WE55bkRraUxwR3p4TjNBK2RreAo0NUpuUGZDODZVTS9ZRnpRVy9zdWszTUhLTk5MSVRtVXNHZzRiTTdSYWNCT29OTm94S0hYTTI5aUE4UU9YRytBCnF2eW4wQ2lNbWN4K0NvSTN2anN2NW83Yk5OU2xvWEtCUlExMFY4VVlXZDd4eENzeDc4cTFLMHRHQUhnZWE0eEoKTW1FRGpRN2I4UXEzZC94Y05EM05ja0JGbU1VbnRVSjlUTHJSYU9WM0V2bDVYcG1JMnl1ZENHVXRuUVhleVgyRApRSHFyOEtiQmJNMGZkUFg4dUJJWVNFL0U4NVYzT294eUJ2UFJLRzRtdUN5OVp1QWFjb0Z5aG1NQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg=={{ end }}
{{ end }}{{/* if not .Values.global.experimental_native_ingress */}}
