name: build
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notify Build
      uses: voxmedia/github-action-slack-notify-build@v1.1.2
      with:
        channel: ci
        status: STARTED
        color: good
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
    - name: Install Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Test
      run: make vendor && make test
    - name: Docker Build
      run: make docker-build
    - name: Notify Slack Success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.2
      with:
        channel: ci
        status: SUCCESS
        color: good
    - name: Notify Slack Fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1.1.2
      with:
        channel: ci
        status: FAILED
        color: danger
